apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexusai-gateway.fullname" . }}-secret
  labels:
    {{- include "nexusai-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  INITIAL_PASSWORD: {{ .Values.secrets.initialPassword | quote }}
