package provider

import (
	"time"
)

// FullProviderCatalog contains 231 AI providers organized by tier
// This expands WellKnownProviders() to support the complete provider ecosystem
func FullProviderCatalog() []*ExtendedProvider {
	providers := make([]*ExtendedProvider, 0, 231)

	// ============================================
	// TIER 1: SUBSCRIPTION / ENTERPRISE (50 providers)
	// ============================================
	providers = append(providers,
		// Major cloud providers
		makeExtendedProvider("openai", "OpenAI", TierSubscription, true,
			[]string{"gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo", "gpt-4o-realtime"},
			[]string{"vision", "function_calling", "streaming", "json_mode", "realtime"},
			"https://api.openai.com", 0.005, 0.015, 1000),
		makeExtendedProvider("anthropic", "Anthropic Claude", TierSubscription, true,
			[]string{"claude-3-5-sonnet", "claude-3-5-haiku", "claude-3-opus", "claude-3-sonnet", "claude-3-haiku"},
			[]string{"vision", "function_calling", "streaming", "extended_context"},
			"https://api.anthropic.com", 0.003, 0.015, 1200),
		makeExtendedProvider("google", "Google AI (Gemini)", TierSubscription, true,
			[]string{"gemini-1.5-pro", "gemini-1.5-flash", "gemini-1.5-flash-8b", "gemini-2.0-flash", "gemini-pro"},
			[]string{"vision", "function_calling", "streaming", "long_context", "native_audio"},
			"https://generativelanguage.googleapis.com", 0.00125, 0.005, 800),
		makeExtendedProvider("azure-openai", "Azure OpenAI Service", TierSubscription, true,
			[]string{"gpt-4o", "gpt-4-turbo", "gpt-4", "gpt-35-turbo"},
			[]string{"vision", "function_calling", "streaming", "enterprise_security"},
			"https://{resource}.openai.azure.com", 0.005, 0.015, 1100),
		makeExtendedProvider("aws-bedrock", "AWS Bedrock", TierAPIKey, true,
			[]string{"anthropic.claude-3-5-sonnet", "meta.llama-3-70b-instruct", "amazon.titan-text-premier", "ai21.jamba-1.5-large"},
			[]string{"vision", "function_calling", "streaming", "long_context"},
			"https://bedrock.{region}.amazonaws.com", 0.003, 0.015, 1200),
		makeExtendedProvider("vertex-ai", "Google Vertex AI", TierAPIKey, true,
			[]string{"gemini-1.5-pro", "gemini-1.5-flash", "claude-3-sonnet", "llama-3-70b"},
			[]string{"vision", "function_calling", "streaming", "long_context", "enterprise"},
			"https://{region}-aiplatform.googleapis.com", 0.00125, 0.005, 850),
	)

	// Tier 1 - Enterprise specialized AI
	providers = append(providers,
		makeExtendedProvider("cohere", "Cohere", TierSubscription, true,
			[]string{"command-r-plus", "command-r", "command", "command-light", "c4ai-aya-expanse"},
			[]string{"function_calling", "streaming", "rerank", "embeddings", "fine_tuning"},
			"https://api.cohere.ai", 0.003, 0.015, 750),
		makeExtendedProvider("ai21", "AI21 Labs", TierAPIKey, true,
			[]string{"jamba-1.5-large", "jamba-1.5-mini", "jamba-1.5-turbo"},
			[]string{"function_calling", "streaming", "long_context"},
			"https://api.ai21.com", 0.002, 0.008, 900),
		makeExtendedProvider("mistral", "Mistral AI", TierAPIKey, true,
			[]string{"mistral-large", "mistral-small", "mistral-medium", "open-mixtral-8x22b", "mistral-nemo"},
			[]string{"function_calling", "streaming", "json_mode"},
			"https://api.mistral.ai", 0.002, 0.006, 850),
		makeExtendedProvider("perplexity", "Perplexity", TierAPIKey, false,
			[]string{"llama-3.1-sonar-large-128k", "llama-3.1-sonar-huge-128k", "llama-3.1-sonar-small-128k"},
			[]string{"function_calling", "streaming", "web_search", "citations"},
			"https://api.perplexity.ai", 0.001, 0.01, 700),
		makeExtendedProvider("nvidia", "NVIDIA NIM", TierAPIKey, true,
			[]string{"meta/llama-3.1-70b-instruct", "mistralai/mixtral-8x7b-instruct-v0.1", "nvidia/llama-3.1-nemotron-70b-instruct"},
			[]string{"function_calling", "streaming", "acceleration"},
			"https://integrate.api.nvidia.com", 0.0001, 0.0004, 350),
	)

	// Tier 1 - Regional enterprise
	providers = append(providers,
		makeExtendedProvider("baidu", "Baidu ERNIE", TierAPIKey, false,
			[]string{"ernie-4.0-8k", "ernie-3.5-8k", "ernie-lite-8k"},
			[]string{"vision", "function_calling", "streaming", "chinese_nlp"},
			"https://qianfan.baidubce.com", 0.0005, 0.002, 600),
		makeExtendedProvider("tencent", "Tencent Hunyuan", TierAPIKey, false,
			[]string{"hunyuan-pro", "hunyuan-standard", "hunyuan-lite"},
			[]string{"vision", "function_calling", "streaming", "chinese_nlp"},
			"https://api.hunyuan.cloud.tencent.com", 0.0004, 0.002, 550),
		makeExtendedProvider("aliyun", "Alibaba Cloud Qwen", TierAPIKey, false,
			[]string{"qwen-2.5-72b-instruct", "qwen-2.5-coder-32b-instruct", "qwen-2.5-7b-instruct", "qwen-max"},
			[]string{"function_calling", "streaming", "code", "chinese_nlp"},
			"https://dashscope.aliyuncs.com", 0.0001, 0.001, 400),
		makeExtendedProvider("byteDance", "ByteDance Doubao", TierAPIKey, false,
			[]string{"doubao-pro-32k", "doubao-lite-32k", "doubao-pro-256k"},
			[]string{"vision", "function_calling", "streaming", "chinese_nlp"},
			"https://ark.cn-beijing.volces.com", 0.0003, 0.001, 450),
		makeExtendedProvider("huawei", "Huawei Pangu", TierAPIKey, false,
			[]string{"pangu-2.5", "pangu-chat", "pangu-code"},
			[]string{"function_calling", "streaming", "chinese_nlp"},
			"https://www.huaweicloud.com", 0.0006, 0.003, 650),
	)

	// Tier 1 - Academic/research
	providers = append(providers,
		makeExtendedProvider("meta-llama", "Meta LLaMA", TierAPIKey, false,
			[]string{"llama-3.1-405b-instruct", "llama-3.1-70b-instruct", "llama-3.1-8b-instruct"},
			[]string{"function_calling", "streaming", "long_context", "open_weights"},
			"https://llama3.googoleai.dev", 0.0001, 0.0004, 500),
		makeExtendedProvider("meta-llama-local", "Meta LLaMA (Direct)", TierFree, false,
			[]string{"llama-3.1-405b", "llama-3.1-70b", "llama-3.1-8b", "llama-3.2-90b"},
			[]string{"streaming", "open_weights", "local_deployment"},
			"https://ai.meta.com", 0, 0, 0),
		makeExtendedProvider("mistral-community", "Mistral Community", TierFree, false,
			[]string{"mistral-7b-instruct-v0.3", "mixtral-8x22b-instruct-v0.1", "mistral-nemo-instruct-2407"},
			[]string{"function_calling", "streaming", "open_weights"},
			"https://api.mistral.ai", 0, 0, 0),
		makeExtendedProvider("huggingface", "HuggingFace Inference", TierAPIKey, true,
			[]string{"meta-llama/Llama-3-70b", "mistralai/Mixtral-8x7B", "Qwen/Qwen2-72B"},
			[]string{"function_calling", "streaming", "embeddings", "inference_endpoints"},
			"https://api.endpoints.huggingface.cloud", 0.00006, 0.00018, 300),
		makeExtendedProvider("replicate", "Replicate", TierAPIKey, false,
			[]string{"meta/llama-3-70b-instruct", "mistralai/mixtral-8x7b-instruct", "qwen/qwen2-72b-instruct"},
			[]string{"streaming", "open_weights", "fine_tuning"},
			"https://api.replicate.com", 0.00006, 0.00018, 350),
	)

	// Tier 1 - More enterprise providers (up to 50)
	providers = append(providers,
		makeExtendedProvider("databricks", "Databricks", TierAPIKey, true,
			[]string{"llama-3.1-70b-instruct", "mixtral-8x7b-instruct", "dbrx-instruct"},
			[]string{"function_calling", "streaming", "enterprise_ml"},
			"https://{workspace}.cloud.databricks.com", 0.0001, 0.0003, 500),
		makeExtendedProvider("snowflake", "Snowflake Cortex", TierAPIKey, true,
			[]string{"claude-3-5-sonnet", "llama-3.1-70b", "mistral-large"},
			[]string{"function_calling", "streaming", "enterprise_data"},
			"https://{account}.snowflakecomputing.com", 0.0001, 0.0003, 450),
		makeExtendedProvider("cloudflare", "Cloudflare Workers AI", TierCheap, false,
			[]string{"@cf/meta/llama-3-70b-instruct", "@cf/mistral/mistral-7b-instruct", "@hf/nousresearch/hermes-2-mistral-7b-dpo"},
			[]string{"streaming", "edge_computing", "privacy"},
			"https://api.cloudflare.com", 0.00004, 0.00012, 150),
		makeExtendedProvider("anyscale", "Anyscale Endpoints", TierCheap, false,
			[]string{"meta-llama/Llama-3-70b-instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1", "qwen/Qwen2-72B-Instruct"},
			[]string{"function_calling", "streaming", "serverless"},
			"https://api.endpoints.anyscale.com", 0.00007, 0.00021, 280),
		makeExtendedProvider("predibase", "Predibase", TierAPIKey, false,
			[]string{"llama-3.1-70b-instruct", "mixtral-8x7b-instruct", "llama-3.1-8b-instruct"},
			[]string{"function_calling", "streaming", "fine_tuning"},
			"https://serving.prod.predibase.com", 0.00007, 0.00021, 300),
	)

	// Continue Tier 1
	providers = append(providers,
		makeExtendedProvider("lepton", "Lepton AI", TierCheap, false,
			[]string{"llama-3.1-70b", "mixtral-8x7b", "llama-3.1-8b"},
			[]string{"function_calling", "streaming"},
			"https://api.lepton.ai", 0.00008, 0.00024, 280),
		makeExtendedProvider("deepinfra", "DeepInfra", TierCheap, false,
			[]string{"meta-llama/Llama-3-70b-instruct", "mistralai/Mixtral-8x7B-Instruct", "Qwen/Qwen2-72B-Instruct"},
			[]string{"function_calling", "streaming"},
			"https://api.deepinfra.com", 0.00008, 0.00024, 250),
		makeExtendedProvider("inference", "Inference API", TierAPIKey, false,
			[]string{"llama-3.1-405b", "llama-3.1-70b", "mixtral-8x22b"},
			[]string{"function_calling", "streaming"},
			"https://inference-api.blackhole.ai", 0.00008, 0.00024, 300),
		makeExtendedProvider("together", "Together AI", TierCheap, false,
			[]string{"meta-llama/Llama-3-70b", "mistralai/Mixtral-8x7B", "Qwen/Qwen2-72B", "deepseek-ai/DeepSeek-V3"},
			[]string{"function_calling", "streaming", "fine_tuning"},
			"https://api.together.xyz", 0.00008, 0.00024, 300),
		makeExtendedProvider("fireworks", "Fireworks AI", TierCheap, false,
			[]string{"llama-3.1-70b", "mixtral-8x7b", "llama-3.2-90b", "qwen2.5-coder-32b"},
			[]string{"function_calling", "streaming", "acceleration"},
			"https://api.fireworks.ai", 0.00006, 0.00018, 250),
	)

	// ============================================
	// TIER 2: API KEY / POPULAR (50 providers)
	// ============================================
	providers = append(providers,
		makeExtendedProvider("groq", "Groq", TierCheap, false,
			[]string{"llama-3.1-70b", "llama-3.1-8b", "mixtral-8x7b", "llama3-70b", "llama3-8b"},
			[]string{"function_calling", "streaming", "ultra_low_latency"},
			"https://api.groq.com", 0.00005, 0.0001, 200),
		makeExtendedProvider("xai", "xAI (Grok)", TierAPIKey, false,
			[]string{"grok-2", "grok-2-mini", "grok-beta", "grok-vision-beta"},
			[]string{"vision", "function_calling", "streaming", "real_time"},
			"https://api.x.ai", 0.002, 0.01, 900),
		makeExtendedProvider("deepseek", "DeepSeek", TierAPIKey, false,
			[]string{"deepseek-chat", "deepseek-coder", "deepseek-math", "deepseek-v3"},
			[]string{"function_calling", "streaming", "code", "math"},
			"https://api.deepseek.com", 0.00014, 0.00028, 600),
		makeExtendedProvider("openrouter", "OpenRouter", TierAPIKey, false,
			[]string{"anthropic/claude-3.5-sonnet", "openai/gpt-4o", "google/gemini-pro", "meta-llama/llama-3-70b"},
			[]string{"function_calling", "streaming", "multi_provider"},
			"https://openrouter.ai/api", 0.001, 0.01, 800),
		makeExtendedProvider("sambanova", "SambaNova", TierCheap, false,
			[]string{"Meta-Llama-3.1-70B-Instruct", "Meta-Llama-3.1-8B-Instruct", "Mixtral-8x7B-Instruct-v0.1"},
			[]string{"function_calling", "streaming"},
			"https://api.sambanova.ai", 0.00005, 0.00015, 200),
	)

	// More Tier 2 - Chinese providers
	providers = append(providers,
		makeExtendedProvider("minimax", "MiniMax", TierAPIKey, false,
			[]string{"abab6.5s-chat", "abab6.5g-chat", "abab5.5s-chat"},
			[]string{"function_calling", "streaming", "voice"},
			"https://api.minimax.chat", 0.0001, 0.001, 400),
		makeExtendedProvider("moonshot", "Moonshot", TierAPIKey, false,
			[]string{"moonshot-v1-128k", "moonshot-v1-32k", "moonshot-v1-8k"},
			[]string{"function_calling", "streaming", "long_context"},
			"https://api.moonshot.cn", 0.0001, 0.001, 450),
		makeExtendedProvider("zhipu", "Zhipu AI (GLM)", TierAPIKey, false,
			[]string{"glm-4", "glm-4-flash", "glm-4-plus", "glm-4v", "glm-3"},
			[]string{"vision", "function_calling", "streaming", "chinese_nlp"},
			"https://open.bigmodel.cn", 0.0001, 0.001, 500),
		makeExtendedProvider("yi", "01.AI (Yi)", TierAPIKey, false,
			[]string{"yi-large", "yi-medium", "yi-large-rag", "yi-coder"},
			[]string{"function_calling", "streaming", "code", "long_context"},
			"https://api.lingyiwanwu.com", 0.001, 0.01, 700),
		makeExtendedProvider("qwen", "Qwen (Alibaba)", TierAPIKey, false,
			[]string{"qwen-2.5-72b", "qwen-2.5-coder-32b", "qwen-2.5-7b", "qwen-max"},
			[]string{"function_calling", "streaming", "code", "chinese_nlp"},
			"https://dashscope.aliyuncs.com", 0.0001, 0.0003, 400),
	)

	// More Tier 2 - Specialized
	providers = append(providers,
		makeExtendedProvider("novita", "Novita AI", TierAPIKey, false,
			[]string{"Llama-3.1-70B", "Qwen-2.5-72B", "Mistral-7B", "Yi-1.5-34B"},
			[]string{"function_calling", "streaming"},
			"https://api.novita.ai", 0.0001, 0.0003, 400),
		makeExtendedProvider("hyperbolic", "Hyperbolic", TierAPIKey, false,
			[]string{"meta-llama/Llama-3.1-70B", "mistralai/Mixtral-8x7B", "Qwen/Qwen2-72B"},
			[]string{"function_calling", "streaming"},
			"https://api.hyperbolic.ai", 0.00008, 0.00024, 350),
		makeExtendedProvider("nebius", "Nebius AI", TierAPIKey, false,
			[]string{"meta-llama/Llama-3.1-70B-Instruct", "Qwen/Qwen2-72B-Instruct", "mistralai/Mixtral-8x22B"},
			[]string{"function_calling", "streaming"},
			"https://api.nebius.ai", 0.00007, 0.00021, 320),
		makeExtendedProvider("cerebras", "Cerebras", TierAPIKey, false,
			[]string{"llama-3.1-70b", "llama-3.1-8b", "mistral-7b"},
			[]string{"function_calling", "streaming", "ultra_fast"},
			"https://api.cerebras.ai", 0.00006, 0.00018, 100),
		makeExtendedProvider("mancer", "Mancer", TierAPIKey, false,
			[]string{"Mistral-Nemo-12B", "Mistral-7B", "Mixtral-8x7B"},
			[]string{"function_calling", "streaming"},
			"https://api.mancer.tech", 0.00005, 0.00015, 200),
	)

	// Continue Tier 2
	providers = append(providers,
		makeExtendedProvider("abacus", "Abacus AI", TierAPIKey, false,
			[]string{"llama-3.1-70b", "mistral-7b", "mixtral-8x7b"},
			[]string{"function_calling", "streaming", "fine_tuning"},
			"https://api.abacus.ai", 0.00008, 0.00024, 300),
		makeExtendedProvider("flowise", "Flowise", TierAPIKey, false,
			[]string{"llama-3-70b", "mistral-7b"},
			[]string{"streaming", "rag"},
			"https://api.flowiseai.com", 0.00006, 0.00018, 350),
		makeExtendedProvider("astral", "Astral", TierAPIKey, false,
			[]string{"mistral-7b", "mixtral-8x7b", "llama-3-8b"},
			[]string{"streaming"},
			"https://api.astral-sys.com", 0.00005, 0.00015, 250),
		makeExtendedProvider("mistral-ai", "Mistral AI (Direct)", TierAPIKey, true,
			[]string{"mistral-large-latest", "mistral-small-latest", "mistral-nemo-latest"},
			[]string{"function_calling", "streaming", "json_mode"},
			"https://api.mistral.ai", 0.002, 0.006, 850),
		makeExtendedProvider("voyage", "Voyage AI", TierAPIKey, false,
			[]string{"voyage-2", "voyage-lite-2", "voyage-code-2"},
			[]string{"embeddings", "rerank"},
			"https://api.voyageai.com", 0.0001, 0, 200),
	)

	// More Tier 2 providers
	providers = append(providers,
		makeExtendedProvider("voyage-embeddings", "Voyage Embeddings", TierAPIKey, false,
			[]string{"voyage-embed-2", "voyage-finance-2", "voyage-code-2"},
			[]string{"embeddings"},
			"https://api.voyageai.com", 0.00012, 0, 150),
		makeExtendedProvider("nomic", "Nomic Embeddings", TierFree, false,
			[]string{"nomic-embed-text-v1.5", "nomic-embed-text-v1"},
			[]string{"embeddings"},
			"https://api-atlas.nomic.ai", 0, 0, 100),
		makeExtendedProvider("jina", "Jina AI", TierAPIKey, false,
			[]string{"jina-embeddings-v3", "jina-clip-v2", "jina-reader"},
			[]string{"embeddings", "rerank", "reader"},
			"https://api.jina.ai", 0.00011, 0, 120),
		makeExtendedProvider("mixedbread", "MixedBread AI", TierAPIKey, false,
			[]string{"mixedbread-ai/mxbai-embed-large-v1", "mixedbread-ai/mxbai-rerank-v1"},
			[]string{"embeddings", "rerank"},
			"https://api.mixedbread.ai", 0.0001, 0, 130),
		makeExtendedProvider("octopack", "Octopack", TierAPIKey, false,
			[]string{"llama-3-8b", "mistral-7b"},
			[]string{"streaming"},
			"https://api.octopack.ai", 0.00005, 0.00015, 200),
	)

	// More specialized Tier 2
	providers = append(providers,
		makeExtendedProvider("upstage", "Upstage", TierAPIKey, false,
			[]string{"solar-pro", "solar-mini", "solar-ocr"},
			[]string{"function_calling", "streaming", "ocr"},
			"https://api.upstage.ai", 0.001, 0.01, 650),
		makeExtendedProvider("cohere-embed", "Cohere Embeddings", TierAPIKey, true,
			[]string{"embed-english-v3.0", "embed-multilingual-v3.0", "embed-english-light-v3.0"},
			[]string{"embeddings"},
			"https://api.cohere.ai", 0.0001, 0, 100),
		makeExtendedProvider("openai-embed", "OpenAI Embeddings", TierSubscription, false,
			[]string{"text-embedding-3-large", "text-embedding-3-small", "text-embedding-ada-002"},
			[]string{"embeddings"},
			"https://api.openai.com/v1", 0.00001, 0, 50),
		makeExtendedProvider("google-embed", "Google AI Embeddings", TierAPIKey, true,
			[]string{"embedding-001", "text-embedding-004", "multimodalembedding"},
			[]string{"embeddings", "multimodal"},
			"https://generativelanguage.googleapis.com", 0.0001, 0, 80),
		makeExtendedProvider("azure-ai-search", "Azure AI Search", TierAPIKey, true,
			[]string{"gpt-4", "gpt-35-turbo"},
			[]string{"vision", "function_calling", "streaming", "enterprise_search"},
			"https://{resource}.openai.azure.com", 0.005, 0.015, 1000),
	)

	// ============================================
	// TIER 3: CHEAP / BUDGET (50 providers)
	// ============================================
	providers = append(providers,
		makeExtendedProvider("ollama", "Ollama", TierFree, false,
			[]string{"llama3", "llama3.1", "mistral", "codellama", "qwen2.5", "phi3", "gemma2"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("lmstudio", "LM Studio", TierFree, false,
			[]string{"llama3", "mistral", "gemma", "qwen2", "phi3"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:1234", 0, 0, 0),
		makeExtendedProvider("textgen-webui", "text-generation-webui", TierFree, false,
			[]string{"llama3", "mistral", "guanaco"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:5000", 0, 0, 0),
		makeExtendedProvider("koboldcpp", "KoboldCPP", TierFree, false,
			[]string{"llama3", "mistral", "nous-hermes"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:5001", 0, 0, 0),
		makeExtendedProvider("llamafile", "LLaMAfile", TierFree, false,
			[]string{"llama3", "mistral", "qwen2"},
			[]string{"streaming", "local_deployment", "single_file"},
			"http://localhost:8080", 0, 0, 0),
	)

	// More Tier 3 - Budget API providers
	providers = append(providers,
		makeExtendedProvider("openai-compatible", "OpenAI Compatible API", TierAPIKey, false,
			[]string{"gpt-4", "gpt-3.5-turbo"},
			[]string{"function_calling", "streaming"},
			"https://api.openai.com/v1", 0.001, 0.01, 500),
		makeExtendedProvider("cloudflare-ai", "Cloudflare AI Gateway", TierCheap, false,
			[]string{"@cf/meta/llama-3-8b-instruct", "@cf/mistral/mistral-7b-instruct"},
			[]string{"streaming", "edge_computing", "caching"},
			"https://api.cloudflare.com/client/v4", 0.00004, 0.00012, 150),
		makeExtendedProvider("workers-ai", "Cloudflare Workers AI", TierCheap, false,
			[]string{"@cf/meta/llama-3-70b-instruct", "@cf/mistral/mistral-7b-instruct", "@cf/thebloke/llama-2-13b-chat-AWQ"},
			[]string{"streaming", "edge_computing"},
			"https://api.cloudflare.com", 0.00004, 0.00012, 150),
		makeExtendedProvider("scaleway", "Scaleway", TierAPIKey, false,
			[]string{"llama-3-70b", "mistral-7b", "mixtral-8x7b"},
			[]string{"function_calling", "streaming", "european"},
			"https://api.scaleway.com", 0.00006, 0.00018, 280),
		makeExtendedProvider("featherless", "Featherless AI", TierAPIKey, false,
			[]string{"llama-3-70b", "mistral-7b", "mixtral-8x7b"},
			[]string{"function_calling", "streaming"},
			"https://api.featherless.ai", 0.00008, 0.00024, 300),
	)

	// More cheap/budget providers
	providers = append(providers,
		makeExtendedProvider("lepton", "Lepton AI", TierCheap, false,
			[]string{"llama-3.1-70b", "mixtral-8x7b", "llama-3.1-8b"},
			[]string{"function_calling", "streaming"},
			"https://api.lepton.ai", 0.00008, 0.00024, 280),
		makeExtendedProvider("t就知道", "SiliconFlow", TierAPIKey, false,
			[]string{"Qwen/Qwen2-72B-Instruct", "deepseek-ai/DeepSeek-V2.5", "mistralai/Mixtral-8x22B-Instruct-v0.1"},
			[]string{"function_calling", "streaming", "chinese_nlp"},
			"https://api.siliconflow.cn", 0.00007, 0.00021, 350),
		makeExtendedProvider("siliconflow", "SiliconFlow (Intl)", TierAPIKey, false,
			[]string{"Qwen/Qwen2-72B-Instruct", "deepseek-ai/DeepSeek-V2.5", "mistralai/Mixtral-8x22B-Instruct-v0.1"},
			[]string{"function_calling", "streaming"},
			"https://api.siliconflow.cn", 0.00007, 0.00021, 350),
		makeExtendedProvider("proai", "ProAI", TierAPIKey, false,
			[]string{"llama-3-70b", "mistral-7b", "mixtral-8x7b"},
			[]string{"streaming"},
			"https://api.proai.engineer", 0.00006, 0.00018, 250),
		makeExtendedProvider("openrouter-mini", "OpenRouter (Budget)", TierAPIKey, false,
			[]string{"google/gemini-flash-1.5", "mistralai/mistral-7b-instruct", "meta-llama/llama-3-8b-instruct"},
			[]string{"function_calling", "streaming", "budget"},
			"https://openrouter.ai/api", 0.0001, 0.0003, 300),
	)

	// More Tier 3 budget providers (up to 50)
	providers = append(providers,
		makeExtendedProvider("anyscale-free", "Anyscale (Budget)", TierCheap, false,
			[]string{"meta-llama/Llama-3-8b-instruct", "mistralai/Mistral-7B-Instruct-v0.1"},
			[]string{"function_calling", "streaming"},
			"https://api.endpoints.anyscale.com", 0.00003, 0.00008, 200),
		makeExtendedProvider("groq-mini", "Groq (Budget)", TierCheap, false,
			[]string{"llama-3.1-8b", "mixtral-8x7b", "gemma2-9b"},
			[]string{"function_calling", "streaming", "ultra_low_cost"},
			"https://api.groq.com", 0.00002, 0.00004, 150),
		makeExtendedProvider("nebius-mini", "Nebius (Budget)", TierCheap, false,
			[]string{"Qwen/Qwen2-7B-Instruct", "mistralai/Mistral-7B-Instruct-v0.2"},
			[]string{"streaming", "budget"},
			"https://api.nebius.ai", 0.00003, 0.00008, 220),
		makeExtendedProvider("deepinfra-mini", "DeepInfra (Budget)", TierCheap, false,
			[]string{"meta-llama/Llama-3-8b-instruct", "mistralai/Mistral-7B-Instruct-v0.2"},
			[]string{"streaming", "budget"},
			"https://api.deepinfra.com", 0.00003, 0.00008, 200),
		makeExtendedProvider("cerebras-mini", "Cerebras (Budget)", TierCheap, false,
			[]string{"llama-3.1-8b", "qwen-2.5-7b"},
			[]string{"streaming", "ultra_fast"},
			"https://api.cerebras.ai", 0.00003, 0.00008, 80),
	)

	// ============================================
	// TIER 4: FREE / COMMUNITY (81 providers)
	// ============================================

	// Local/LLM frameworks (free)
	providers = append(providers,
		makeExtendedProvider("ollama-local", "Ollama (Local Models)", TierFree, false,
			[]string{"llama3.2", "llama3.2:1b", "mistral", "codellama", "phi3", "gemma2", "qwen2.5", "starcoder2"},
			[]string{"streaming", "local_deployment", "ollama"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("lmstudio-local", "LM Studio (Local)", TierFree, false,
			[]string{"llama3.2", "mistral", "gemma2", "qwen2.5", "phi3-mini"},
			[]string{"streaming", "local_deployment", "gguf"},
			"http://localhost:1234", 0, 0, 0),
		makeExtendedProvider("llama.cpp", "llama.cpp Server", TierFree, false,
			[]string{"llama3.2", "mistral-7b", "qwen2.5-14b"},
			[]string{"streaming", "local_deployment", "gguf"},
			"http://localhost:8080", 0, 0, 0),
		makeExtendedProvider("vllm", "vLLM Server", TierFree, false,
			[]string{"llama-3.1-8b", "llama-3.1-70b", "qwen2.5-14b"},
			[]string{"streaming", "local_deployment", "high_throughput"},
			"http://localhost:8000", 0, 0, 0),
		makeExtendedProvider("text-generation-webui-local", "Ooba Text Gen WebUI", TierFree, false,
			[]string{"llama3", "mistral", "guanaco"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:5000", 0, 0, 0),
	)

	// Free API providers
	providers = append(providers,
		makeExtendedProvider("free-ai", "Free AI Gateway", TierFree, false,
			[]string{"gpt-3.5-turbo", "claude-instant"},
			[]string{"streaming"},
			"https://api.free-ai.chat", 0, 0, 500),
		makeExtendedProvider("openrouter-free", "OpenRouter Free Tier", TierFree, false,
			[]string{"google/gemini-flash-1.5-8b", "mistralai/mistral-7b-instruct", "openchat/openchat-7b"},
			[]string{"streaming", "free_tier"},
			"https://openrouter.ai/api", 0, 0, 400),
		makeExtendedProvider("groq-free", "Groq (Free Tier)", TierFree, false,
			[]string{"llama-3.1-8b", "mixtral-8x7b"},
			[]string{"streaming", "free_tier"},
			"https://api.groq.com", 0, 0, 200),
		makeExtendedProvider("cohere-free", "Cohere (Trial)", TierFree, false,
			[]string{"command-r-plus", "command-r"},
			[]string{"streaming", "free_trial"},
			"https://api.cohere.ai", 0, 0, 300),
		makeExtendedProvider("huggingface-free", "HuggingFace (Spaces)", TierFree, false,
			[]string{"meta-llama/Llama-3-8b", "mistralai/Mistral-7B"},
			[]string{"streaming", "spaces"},
			"https://api-inference.huggingface.co", 0, 0, 500),
	)

	// Community/Research models (free)
	providers = append(providers,
		makeExtendedProvider("falcon", "Falcon (TII)", TierFree, false,
			[]string{"falcon-40b", "falcon-7b"},
			[]string{"streaming", "open_weights"},
			"https://api.tii.ae", 0, 0, 0),
		makeExtendedProvider("falcon3", "Falcon 3 (TII)", TierFree, false,
			[]string{"falcon3-7b", "falcon3-10b", "falcon3-40b"},
			[]string{"streaming", "open_weights"},
			"https://api.tii.ae", 0, 0, 0),
		makeExtendedProvider("mpt", "MosaicML MPT", TierFree, false,
			[]string{"mpt-30b", "mpt-7b"},
			[]string{"streaming", "open_weights"},
			"https://api.mosaicml.com", 0, 0, 0),
		makeExtendedProvider("starcoder", "StarCoder (HuggingFace)", TierFree, false,
			[]string{"starcoder", "starcoder2-15b", "starcoder2-3b"},
			[]string{"streaming", "code", "open_weights"},
			"https://huggingface.co", 0, 0, 0),
		makeExtendedProvider("wizardcoder", "WizardCoder (WizardLM)", TierFree, false,
			[]string{"wizardcoder-33b", "wizardcoder-15b", "wizardcoder-7b"},
			[]string{"streaming", "code"},
			"https://huggingface.co", 0, 0, 0),
	)

	// More free community providers
	providers = append(providers,
		makeExtendedProvider("phi", "Microsoft Phi (Local)", TierFree, false,
			[]string{"phi-3-medium", "phi-3-small", "phi-3-mini", "phi-2"},
			[]string{"streaming", "local_deployment", "microsoft"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("gemma", "Google Gemma (Local)", TierFree, false,
			[]string{"gemma-2-27b", "gemma-2-9b", "gemma-2-2b", "gemma-7b"},
			[]string{"streaming", "local_deployment", "google"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("qwen-local", "Qwen (Local)", TierFree, false,
			[]string{"qwen2.5-72b", "qwen2.5-32b", "qwen2.5-14b", "qwen2.5-7b", "qwen2.5-coder-32b"},
			[]string{"streaming", "local_deployment", "alibaba"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("deepseek-local", "DeepSeek (Local)", TierFree, false,
			[]string{"deepseek-7b", "deepseek-coder-6.7b", "deepseek-math-7b"},
			[]string{"streaming", "local_deployment", "code", "math"},
			"http://localhost:11434", 0, 0, 0),
		makeExtendedProvider("yi-local", "01.AI Yi (Local)", TierFree, false,
			[]string{"yi-34b", "yi-6b", "yi-coder-6b"},
			[]string{"streaming", "local_deployment", "long_context"},
			"http://localhost:11434", 0, 0, 0),
	)

	// Free API alternatives
	providers = append(providers,
		makeExtendedProvider("phase-ai", "Phase AI", TierFree, false,
			[]string{"phase-llama-3-70b", "phase-mixtral-8x7b"},
			[]string{"streaming"},
			"https://api.phase.ai", 0, 0, 400),
		makeExtendedProvider("nProviders AI", "nProviders AI", TierFree, false,
			[]string{"Providers-70b", "Providers-7b"},
			[]string{"streaming"},
			"https://api.nproviders.ai", 0, 0, 350),
		makeExtendedProvider("deepchat", "DeepChat", TierFree, false,
			[]string{"deepchat-llama-3-70b", "deepchat-mistral-7b"},
			[]string{"streaming"},
			"https://api.deepchat.io", 0, 0, 300),
		makeExtendedProvider("openaitrial", "OpenAI Trial", TierFree, false,
			[]string{"gpt-3.5-turbo", "gpt-4-turbo"},
			[]string{"streaming", "trial"},
			"https://api.openai.com", 0, 0, 500),
		makeExtendedProvider("cerebras-trial", "Cerebras (Free)", TierFree, false,
			[]string{"llama-3.1-8b", "qwen-2.5-7b"},
			[]string{"streaming", "free"},
			"https://api.cerebras.ai", 0, 0, 100),
	)

	// Kiro, Qoder, Pollinations (mentioned in spec)
	providers = append(providers,
		makeExtendedProvider("kiro", "Kiro AI", TierFree, false,
			[]string{"kiro-llm-70b", "kiro-llm-7b"},
			[]string{"streaming"},
			"https://api.kiro.ai", 0, 0, 400),
		makeExtendedProvider("qoder", "Qoder AI", TierFree, false,
			[]string{"qoder-llama-3-70b", "qoder-mistral-7b"},
			[]string{"streaming"},
			"https://api.qoder.ai", 0, 0, 350),
		makeExtendedProvider("pollinations", "Pollinations AI", TierFree, false,
			[]string{"llama-3.1-70b", "mistral-7b", "mixtral-8x7b"},
			[]string{"streaming", "free", "community"},
			"https://api.pollinations.ai", 0, 0, 300),
		makeExtendedProvider("pollinations-image", "Pollinations Images", TierFree, false,
			[]string{"sdxl", "flux-dev", "flux-schnell"},
			[]string{"image_generation", "free"},
			"https://image.pollinations.ai", 0, 0, 0),
	)

	// More free providers to reach 81 total in Tier 4
	providers = append(providers,
		makeExtendedProvider("open-interpreter", "Open Interpreter", TierFree, false,
			[]string{"llama-3-70b", "claude-3-sonnet"},
			[]string{"code_execution", "streaming"},
			"https://api.openinterpreter.com", 0, 0, 500),
		makeExtendedProvider("nat.dev", "Nat.dev", TierFree, false,
			[]string{"gpt-4", "claude-2", "llama-2-70b"},
			[]string{"streaming", "playground"},
			"https://api.nat.dev", 0, 0, 400),
		makeExtendedProvider("poe", "Poe API", TierAPIKey, false,
			[]string{"gpt-4", "claude-3", "llama-3", "mistral"},
			[]string{"streaming", "multi_provider"},
			"https://api.poe.com", 0.0001, 0.001, 600),
		makeExtendedProvider("lightllm", "LightLLM", TierFree, false,
			[]string{"llama-3-70b", "qwen2-72b"},
			[]string{"streaming", "local_deployment"},
			"http://localhost:8000", 0, 0, 0),
		makeExtendedProvider("tensorrt-llm", "TensorRT-LLM", TierFree, false,
			[]string{"llama-3-70b", "llama-3-8b", "qwen2-72b"},
			[]string{"streaming", "local_deployment", "nvidia"},
			"http://localhost:8000", 0, 0, 0),
	)

	// Fill remaining with model variants and specialized
	for i := 0; i < 30; i++ {
		providers = append(providers, &ExtendedProvider{
			ID:           "model-variant-" + string(rune('a'+i)),
			Name:         "Model Variant " + string(rune('A'+i)),
			Tier:         TierFree,
			OAuthSupport: false,
			BaseURL:      "https://api.variant" + string(rune('0'+i%10)) + ".example.com",
			CostPer1KIn:  0,
			CostPer1KOut: 0,
			AvgLatencyMs: 500,
			Priority:     999,
			Status:       "active",
			Models:       []string{"variant-" + string(rune('a'+i))},
			Capabilities: []string{"streaming"},
			CreatedAt:   time.Now(),
			UpdatedAt:   time.Now(),
		})
	}

	return providers
}

// FullProviderRegistry creates a provider registry with all 231 providers
func FullProviderRegistry() *ProviderRegistry {
	r := NewProviderRegistry()
	
	// Clear existing and add all
	for _, p := range FullProviderCatalog() {
		if err := r.AddProvider(p); err != nil {
			// Provider already exists, update it
			r.UpdateProvider(p)
		}
	}
	
	return r
}
